apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
        - name: apache2
          image: gmedeirosnet/apache2-gmedeiros
          ports:
            - containerPort: 80