apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-pod
          ## Alterando a imagem pelo Docker HUB
          image: nginx:latest
          #image: gmedeirosnet/apache2-gmedeiros
          ports:
            - containerPort: 80