apiVersion: v1
kind: Pod
metadata:
  name: apache2
  labels:
    name: apache2
spec:
  containers:
  - name: apache2
    image: gmedeirosnet/apache2-gmedeiros
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: apache2-volume
        mountPath: /var/www/html
  volumes:
    - name: apache2-volume
      persistentVolumeClaim:
        claimName: apache2-pvc