apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: nginx-volume
        mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-volume
      persistentVolumeClaim:
        claimName: nginx-pvc